use_frameworks!

target 'SAPinViewController_Example' do
  pod 'SAPinViewController', :path => '../'
  pod 'SnapKit'
  target 'SAPinViewController_Tests' do
    inherit! :search_paths

    
  end
end
